version: '3.8'
services:
  db-mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=dashboard
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
