FROM gradle:8.8-jdk22 AS build
WORKDIR /home/gradle/src
COPY --chown=gradle:gradle . .
RUN gradle build --no-daemon

# Stage 2: Run
FROM eclipse-temurin:22-jre-alpine
WORKDIR /app
COPY --from=build /home/gradle/src/build/libs/*.jar /app/spring-boot-application.jar
COPY config/application.properties /app/config/application.properties

EXPOSE 7000

ENTRYPOINT ["java", "-jar", "/app/spring-boot-application.jar", "--spring.config.location=/app/config/application.properties"]